# Generated by Django 5.1.7 on 2025-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('38', 'EU 38'), ('39', 'EU 39'), ('40', 'EU 40'), ('41', 'EU 41'), ('42', 'EU 42'), ('43', 'EU 43'), ('44', 'EU 44'), ('45', 'EU 45'), ('46', 'EU 46')], max_length=5, null=True),
        ),
    ]
